[package]
name = "builder"
version = "0.1.0"
authors = ["Emma Turner <em.turner@tutanota.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
